data:
  module_name: data_loaders.mnist_labeled
  class_name: MnistDataLoaderFactory
  root: ./data
  batch_size: 128

discriminator:
  module_name: models.labeled.conv_discriminator
  class_name: ConvDiscriminator
#  dropout: 0.5

generator:
  module_name: models.labeled.conv_generator_v2
  class_name: ConvGeneratorV2

trainer:
  module_name: trainers.labeled.discriminator_noise
  class_name: DiscriminatorNoiseTrainer
  checkpoint_steps: 50
  noise_sigma: 0.2
  discriminator:
    training_batches: 1
    optimizer_args:
      lr: 2.0e-4
      weight_decay: 1.0e-3
  generator:
    training_batches: 1
    optimizer_args:
      lr: 1.0e-4
      weight_decay: 1.0e-2
  steps: 2000

experiment:
  save: True

device: cuda
