data:
  module_name: data_loaders.mnist
  class_name: MnistDataLoaderFactory
  root: /tmp/data
  batch_size: 128

discriminator:
  module_name: models.conv_discriminator_batchnorm
  class_name: ConvDiscriminatorBatchnorm
#  dropout: 0.5

generator:
  module_name: models.conv_generator
  class_name: ConvGenerator

trainer:
  module_name: trainers.discriminator_noise
  class_name: DiscriminatorNoiseTrainer
  checkpoint_steps: 200
  label_smoothing: 0.9
  noise_sigma: 0.3
  discriminator:
    training_batches: 1
    lr: 2.0e-4
  generator:
    training_batches: 1
    lr: 1.0e-4
  steps: 10000

experiment:
  save: True

device: cuda
