data:
  module_name: data_loaders.mnist
  class_name: MnistDataLoaderFactory
  root: /tmp/data
  batch_size: 128

discriminator:
  module_name: models.conv_discriminator_large
  class_name: ConvDiscriminator
  dropout: 0.5

generator:
  module_name: models.conv_generator
  class_name: ConvGenerator

trainer:
  module_name: trainers.default_trainer
  class_name: DefaultTrainer
  checkpoint_steps: 100
  discriminator:
    training_batches: 3
    lr: 1.0e-4
  generator:
    training_batches: 3
    lr: 1.0e-4
  steps: 2000

experiment:
  save: True

device: cuda
